# Default values for zforums
replicaCount: 2

image:
  repository: ghcr.io/rohitmr619/zforums
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 1001

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1001

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  hosts:
    - host: zforums.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: zforums-tls
      hosts:
        - zforums.local

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

# PostgreSQL configuration
postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    postgresPassword: "SecurePassword123!"
    username: "zforums"
    password: "ZForumsPassword123!"
    database: "zforums"
  architecture: standalone
  primary:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: "local-path"
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m

# Environment variables for the application
env:
  - name: NODE_ENV
    value: "production"
  - name: PORT
    valueFrom:
      secretKeyRef:
        name: zforums-secrets
        key: PORT
  - name: DB_HOST
    valueFrom:
      secretKeyRef:
        name: zforums-secrets
        key: DB_HOST
  - name: DB_PORT
    valueFrom:
      secretKeyRef:
        name: zforums-secrets
        key: DB_PORT
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: zforums-secrets
        key: DB_NAME
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: zforums-secrets
        key: DB_USER
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: zforums-secrets
        key: DB_PASSWORD
